using System;
using System.Collections.Generic;
using System.Linq;

namespace NSqlTools.BusinessLayer.Intellisense
{
    public static class TSqlReservedKeywordsProvider
    {
        // Keyword list for simple IntelliSense (SQL Server reserved + common).
        private static readonly string[] Keywords = new[]
        {
            "ADD","EXTERNAL","PROCEDURE","ALL","FETCH","PUBLIC","ALTER","FILE","RAISERROR","AND","FILLFACTOR","READ",
            "ANY","FOR","READTEXT","AS","FOREIGN","RECONFIGURE","ASC","FREETEXT","REFERENCES","AUTHORIZATION","FREETEXTTABLE",
            "REPLICATION","BACKUP","FROM","RESTORE","BEGIN","FULL","RESTRICT","BETWEEN","FUNCTION","RETURN","BREAK",
            "GOTO","REVERT","BROWSE","GRANT","REVOKE","BULK","GROUP","RIGHT","BY","HAVING","ROLLBACK","CASCADE","HOLDLOCK",
            "ROWCOUNT","CASE","IDENTITY","ROWGUIDCOL","CHECK","IDENTITY_INSERT","RULE","CHECKPOINT","IDENTITYCOL","SAVE",
            "CLOSE","IF","SCHEMA","CLUSTERED","IN","SECURITYAUDIT","COALESCE","INDEX","SELECT","COLLATE","INNER","SEMANTICKEYPHRASETABLE",
            "COLUMN","INSERT","SEMANTICPROPERTYLIST","COMMIT","INTERSECT","SEMANTICSIMILARITYDETAILSTABLE","COMPUTE","INTO",
            "SEMANTICSIMILARITYTABLE","CONSTRAINT","IS","SESSION_USER","CONTAINS","JOIN","SET","CONTAINSTABLE","KEY","SETUSER",
            "CONTINUE","KILL","SHUTDOWN","CONVERT","LEFT","SOME","CREATE","LIKE","STATISTICS","CROSS","LINENO","SYSTEM_USER",
            "CURRENT","LOAD","TABLE","CURRENT_DATE","MERGE","TABLESAMPLE","CURRENT_TIME","NATIONAL","TEXTSIZE","CURRENT_TIMESTAMP",
            "NOCHECK","THEN","CURRENT_USER","NONCLUSTERED","TO","CURSOR","NOT","TOP","DATABASE","NULL","TRAN","DBCC","NULLIF",
            "TRANSACTION","DEALLOCATE","OF","TRIGGER","DECLARE","OFF","TRUNCATE","DEFAULT","OFFSETS","TRY_CONVERT","DELETE",
            "ON","TSEQUAL","DENY","OPEN","UNION","DESC","OPENDATASOURCE","UNIQUE","DISK","OPENQUERY","UNPIVOT","DISTINCT",
            "OPENROWSET","UPDATE","DISTRIBUTED","OPENXML","UPDATETEXT","DOUBLE","OPTION","USE","DROP","OR","USER","DUMP",
            "ORDER","VALUES","ELSE","OUTER","VARYING","END","OVER","VIEW","ERRLVL","PERCENT","WAITFOR","ESCAPE","PIVOT","WHEN",
            "EXCEPT","PLAN","WHERE","EXEC","PRECISION","WHILE","EXECUTE","PRIMARY","WITH","EXISTS","PRINT","WITHIN GROUP",
            "EXIT","PROC","WRITETEXT"
        };

        public static IEnumerable<string> GetAll() => Keywords;
    }
}